<?php

function my_acf_init() {
  acf_update_setting('google_api_key', 'AIzaSyBs3x5sifohlp4Zqy3GxSv-oOF0_z2mx9s');
}

add_action('acf/init', 'my_acf_init');

if( function_exists('acf_add_local_field_group') ):


acf_add_local_field_group(array (
  'key' => 'group_581367f629862',
  'title' => 'Lier des pages (accueil, éditions, pages & weekends)',
  'fields' => array (
    array (
      'key' => 'field_5805cd3069666',
      'label' => 'Grille',
      'name' => 'grid',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Ajouter un élément',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '5805cfc08e13a',
          'name' => 'weekend',
          'label' => 'Un weekend',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5805cfd98da2a',
              'label' => 'Quel weekend ?',
              'name' => 'weekend_item',
              'type' => 'post_object',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'weekend',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => '',
              'multiple' => '',
              'return_format' => '',
              'ui' => 1,
            ),
            array (
              'key' => 'field_5805cff88da2b',
              'label' => 'Un titre ?',
              'name' => 'weekend_title',
              'type' => 'text',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5805d01a8da2c',
              'label' => 'Un chapo ?',
              'name' => 'weekend_intro',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => '',
            ),
            array (
              'key' => 'field_5805fe20d32ca',
              'label' => 'Visuel',
              'name' => 'weekend_img',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5805d301e12c2',
          'name' => 'btn_show_events',
          'label' => 'Bouton pour afficher la liste des expositions',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5805d321e12c3',
              'label' => 'Chapo',
              'name' => 'btn_chapo',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '580e18cc030e4',
          'name' => 'affiche',
          'label' => 'Affiche',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_580e18cc030e5',
              'label' => 'Fichier affiche',
              'name' => 'file',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5805d1b4b2d84',
          'name' => 'page',
          'label' => 'Une page',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5805d1b4b2d85',
              'label' => 'Quel page ?',
              'name' => 'page_item',
              'type' => 'post_object',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'page',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => '',
              'multiple' => '',
              'return_format' => '',
              'ui' => 1,
            ),
            array (
              'key' => 'field_5805d1b4b2d86',
              'label' => 'Un titre ?',
              'name' => 'page_title',
              'type' => 'text',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5805d1b4b2d87',
              'label' => 'Un chapo ?',
              'name' => 'page_intro',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => '',
              'conditional_logic' => '',
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5805d1d3b2d88',
          'name' => 'edition',
          'label' => 'Une Edition',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5805d1d4b2d89',
              'label' => 'Quelle edition ?',
              'name' => 'edition_item',
              'type' => 'post_object',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'edition',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => 1,
              'multiple' => 1,
              'return_format' => 'object',
              'ui' => 1,
            ),
            array (
              'key' => 'field_5805d1d4b2d8a',
              'label' => 'Un titre ?',
              'name' => 'edition_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5805d1d4b2d8b',
              'label' => 'Un chapo ?',
              'name' => 'edition_intro',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5805d10d5bb26',
          'name' => 'post',
          'label' => 'Un article',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5805d10d5bb27',
              'label' => 'Quel article ?',
              'name' => 'post_item',
              'type' => 'page_link',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'post',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => 0,
              'allow_archives' => 1,
              'multiple' => 0,
            ),
            array (
              'key' => 'field_5805d15c5bb2a',
              'label' => 'Un titre ?',
              'name' => 'post_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5805d10d5bb29',
              'label' => 'Un chapo ?',
              'name' => 'post_intro',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5805d0398da2d',
          'name' => 'text',
          'label' => 'Un bloc texte simple',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5805d0398da2f',
              'label' => 'Un titre ?',
              'name' => 'text_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5805d0398da30',
              'label' => 'Un chapo ?',
              'name' => 'text_intro',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
            array (
              'key' => 'field_5805d04a8da31',
              'label' => 'Un lien ?',
              'name' => 'text_link',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58060ff8b72fb',
          'name' => 'big_bloc',
          'label' => 'Un grand bloc avec image',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_58061008b72fc',
              'label' => 'Titre',
              'name' => 'big_bloc_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5806101cb72fd',
              'label' => 'Visuel',
              'name' => 'big_bloc_img',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_5806102bb72fe',
              'label' => 'Texte',
              'name' => 'big_bloc_text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
            array (
              'key' => 'field_5806155309de3',
              'label' => 'Lien / Fichier',
              'name' => 'lien__fichier',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
    array (
      'key' => 'field_57c6850ff139f',
      'label' => 'Evénéments & Pages liés',
      'name' => 'evenements_lies',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'event',
        1 => 'post',
        2 => 'page',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'object',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'weekend',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'edition',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-accueil.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));



acf_add_local_field_group(array (
  'key' => 'group_5822ed590285f',
  'title' => 'Détails sur les Pages',
  'fields' => array (
    array (
      'key' => 'field_5822ed6864b8d',
      'label' => 'Chapo',
      'name' => 'chapo',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));


acf_add_local_field_group(array (
  'key' => 'group_57b5be40da406',
  'title' => 'Informations détailées de l\'événement',
  'fields' => array (
    array (
      'key' => 'field_57c683d078f13',
      'label' => 'Auteur & titres',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57c683f478f14',
      'label' => 'Auteur(s)',
      'name' => 'auteurs',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'auteur',
      'field_type' => 'multi_select',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'id',
      'multiple' => 0,
    ),
    array (
      'key' => 'field_57b5c09e8ce73',
      'label' => 'Sous-titres (optionnels)',
      'name' => 'sous_titres',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'table',
      'button_label' => 'Ajouter un sous-titre',
      'sub_fields' => array (
        array (
          'key' => 'field_57b5c0b18ce74',
          'label' => 'Sous-Titre',
          'name' => 'sous-titre',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
    array (
      'key' => 'field_5805e30c8fb0c',
      'label' => 'Chapo',
      'name' => 'chapo',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
    array (
      'key' => 'field_57b5be55d3c3f',
      'label' => 'Infos lieu : dates & horaires',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57b5c05795a55',
      'label' => 'Lieux de l\'événement',
      'name' => 'lieu',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'place',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
    array (
      'key' => 'field_57b5be68d3c40',
      'label' => 'Date fixe ?',
      'name' => 'date_fixe',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_57b5be76d3c41',
      'label' => 'Date',
      'name' => 'date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_57b5be68d3c40',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'd/m/Y',
      'return_format' => 'd/m/Y',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_57b5bebad3c42',
      'label' => 'Date de début',
      'name' => 'date_debut',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_57b5be68d3c40',
            'operator' => '!=',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'd/m/Y',
      'return_format' => 'd/m/Y',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_57b5bed3d3c43',
      'label' => 'Date de fin',
      'name' => 'date_fin',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_57b5be68d3c40',
            'operator' => '!=',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => 50,
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'd/m/Y',
      'return_format' => 'd/m/Y',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_57b5bf32dac36',
      'label' => 'Date de vernissage',
      'name' => 'date_vernissage',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '75',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'd/m/Y',
      'return_format' => 'd/m/Y',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_57b5bf08dac35',
      'label' => 'Horaires',
      'name' => 'horaires',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'wpautop',
    ),
    array (
      'key' => 'field_57cfc636d4ff8',
      'label' => 'Tarifs & Conditions d\'accès',
      'name' => 'tarifs',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'wpautop',
    ),
    array (
      'key' => 'field_57b5bf44dac37',
      'label' => 'Commissariat & Partenaires',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57b5bf5cdac38',
      'label' => 'Nom du commissaire',
      'name' => 'nom_commissaire',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_57b5bfb3efb7a',
      'label' => 'Mentions partenaires & remerciements',
      'name' => 'mentions',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
    array (
      'key' => 'field_57b5bfd4efb7b',
      'label' => 'Catalogue',
      'name' => 'catalogue',
      'type' => 'textarea',
      'instructions' => 'Champ optionnel / Indiquer les mentions complètes du catalogue.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 6,
      'new_lines' => 'wpautop',
    ),
    array (
      'key' => 'field_57c429f27b025',
      'label' => 'Visuels',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57c429fd7b026',
      'label' => 'Sélection de visuels',
      'name' => 'visuels',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'min' => '',
      'max' => '',
      'insert' => 'append',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_57c683574af49',
      'label' => 'Curiosités & événements liés',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57c6836b4af4a',
      'label' => 'La/les curiosité(s) liée(s) à l\'événement',
      'name' => 'curiosites_liste',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'curiosite',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
    array (
      'key' => 'field_57c6850ff139f',
      'label' => 'Evénéments liés',
      'name' => 'evenements_lies',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'event',
        1 => 'post',
        2 => 'page',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'object',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'event',
      ),
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'event',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57c682e85fba3',
  'title' => 'Informations détaillées sur la Curiosité',
  'fields' => array (
    array (
      'key' => 'field_57c682f408a27',
      'label' => 'Description',
      'name' => 'description',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
    array (
      'key' => 'field_57c682ff08a28',
      'label' => 'Adresse de la curiosité',
      'name' => 'adresse',
      'type' => 'google_map',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'center_lat' => '',
      'center_lng' => '',
      'zoom' => '',
      'height' => '',
    ),
    array (
      'key' => 'field_57c6c363a9d2b',
      'label' => 'Type de curiosité',
      'name' => 'type_de_curiosite',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'curiosite-cat',
      'field_type' => 'multi_select',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'id',
      'multiple' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'curiosite',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'author',
    5 => 'format',
    6 => 'page_attributes',
    7 => 'categories',
    8 => 'tags',
    9 => 'send-trackbacks',
  ),
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57b5b658d2a01',
  'title' => 'Informations détaillées sur le lieu d\'exposition',
  'fields' => array (
    array (
      'key' => 'field_57b5b8bba5b0a',
      'label' => 'Infos pratiques',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57b5b6762f80b',
      'label' => 'Adresse',
      'name' => 'adresse',
      'type' => 'google_map',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'center_lat' => '48.859586',
      'center_lng' => '2.353994',
      'zoom' => 11,
      'height' => 300,
    ),
    array (
      'key' => 'field_57b5c1406b942',
      'label' => 'Complément d\'adresse',
      'name' => 'complement_adresse',
      'type' => 'textarea',
      'instructions' => 'ex : "En bas à droite après la cour".',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 5,
      'new_lines' => 'wpautop',
    ),
    array (
      'key' => 'field_57b70be37b12c',
      'label' => 'Type de lieu',
      'name' => 'type_de_lieu',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'place-type',
      'field_type' => 'checkbox',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'id',
      'multiple' => 0,
    ),
    array (
      'key' => 'field_57b5b6842f80c',
      'label' => 'Transport public',
      'name' => 'transport',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 5,
      'new_lines' => 'wpautop',
    ),
    array (
      'key' => 'field_57b5b6c52f810',
      'label' => 'Conditions d\'accès',
      'name' => 'accès',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => 5,
      'new_lines' => 'wpautop',
    ),
    array (
      'key' => 'field_57b5b6912f80d',
      'label' => 'Téléphone',
      'name' => 'telephone',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '33',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_57b5b6a02f80e',
      'label' => 'Email',
      'name' => 'email',
      'type' => 'email',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '33',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    array (
      'key' => 'field_57b5b6d62f811',
      'label' => 'Site web',
      'name' => 'website',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '33',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_57b5b6f32f812',
      'label' => 'Contact',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_57b5b6ff2f813',
      'label' => 'Nom du contact',
      'name' => 'nom_contact',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_57b5b70c2f814',
      'label' => 'Email du contact',
      'name' => 'email_contact',
      'type' => 'email',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    array (
      'key' => 'field_57b70a5e974f7',
      'label' => 'lat & lng (ne pas toucher)',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_582add14a5b28',
      'label' => 'latitude',
      'name' => 'lat',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array (
      'key' => 'field_582add14a5b29',
      'label' => 'longitude',
      'name' => 'lng',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),

  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'place',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'author',
    5 => 'format',
    6 => 'categories',
    7 => 'tags',
    8 => 'send-trackbacks',
  ),
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_5805cce76752b',
  'title' => 'Infos Accueil',
  'fields' => array (
    array (
      'key' => 'field_5805ccf669665',
      'label' => 'Edition courante',
      'name' => 'edition_courante',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'edition',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
    array (
      'key' => 'field_581af71d7b548',
      'label' => 'Afficher les actualités ?',
      'name' => 'display_news',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_580616a2b090f',
      'label' => 'Actualité principale',
      'name' => 'news_main',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'post',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
    ),
    array (
      'key' => 'field_580e231fd6f52',
      'label' => 'Partenaires',
      'name' => 'partenaires',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
    array (
      'key' => 'field_581301e5a6289',
      'label' => 'Bouttons pour mobile',
      'name' => 'bouttons_pour_mobile',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Ajouter un élément',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '581302051973b',
          'name' => 'liste_des_expositions',
          'label' => 'Liste des expositions (toutes ou près de moi)',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5813021ba628a',
              'label' => 'Texte du bouton',
              'name' => 'texte',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_58130286a628f',
              'label' => 'Action',
              'name' => 'action',
              'type' => 'text',
              'instructions' => '"js-display-events" pour toutes les expositions<br>
"js-display-aroundme" pour les expos aux alentours',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58130231a628b',
          'name' => 'lien_vers_page',
          'label' => 'Lien vers page',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5813023fa628c',
              'label' => 'Texte du bouton',
              'name' => 'texte',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5813024ea628d',
              'label' => 'Page liée',
              'name' => 'page',
              'type' => 'page_link',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
              ),
              'taxonomy' => array (
              ),
              'allow_null' => 0,
              'allow_archives' => 1,
              'multiple' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-accueil.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'author',
    5 => 'format',
    6 => 'categories',
    7 => 'tags',
  ),
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57beb07017eb7',
  'title' => 'Infos auteur',
  'fields' => array (
    array (
      'key' => 'field_57beb0918aa87',
      'label' => 'Biographie',
      'name' => 'biographie',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'taxonomy',
        'operator' => '==',
        'value' => 'auteur',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57beaa92d19f2',
  'title' => 'Infos média',
  'fields' => array (
    array (
      'key' => 'field_57beaabdad50e',
      'label' => 'Légende complète',
      'name' => 'legende',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'attachment',
        'operator' => '==',
        'value' => 'all',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_5804e50b2b338',
  'title' => 'Infos sur l\'édition',
  'fields' => array (
    array (
      'key' => 'field_5804e517b10cc',
      'label' => 'Edition courante ?',
      'name' => 'edition_courante',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 1,
    ),
    array (
      'key' => 'field_5804e5a0b10cf',
      'label' => 'Que voulez-vous lier à cette édition ? Des événements ou des weekends ?',
      'name' => 'type_relation',
      'type' => 'select',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5804e517b10cc',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'Weekends' => 'Weekends',
        'Événements' => 'Événements',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_5804e538b10cd',
      'label' => 'Weekends liés',
      'name' => 'weekends',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5804e5a0b10cf',
            'operator' => '==',
            'value' => 'Weekends',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'weekend',
      ),
      'taxonomy' => array (
      ),
      'filters' => '',
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
    array (
      'key' => 'field_5804e57fb10ce',
      'label' => 'Evenements liés',
      'name' => 'evenements',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5804e5a0b10cf',
            'operator' => '==',
            'value' => 'Événements',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'event',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'edition',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_5805d475c6f3e',
  'title' => 'Infos sur le weekend',
  'fields' => array (
    array (
      'key' => 'field_5805d4805c0fe',
      'label' => 'Les expositions liées au weekend',
      'name' => 'events_list',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'event',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'id',
    ),
    array (
      'key' => 'field_5805d4805c0ff',
      'label' => 'Afficher les actualités ?',
      'name' => 'display_news',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_580e251c7be05',
      'label' => 'Couleur du weekend',
      'name' => 'color',
      'type' => 'color_picker',
      'instructions' => '#283583 pour le bleu
#DB0819 pour le rouge
#3FA535 pour le vert
#000000 pour le noir',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'weekend',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));



acf_add_local_field_group(array (
  'key' => 'group_581886b07b085',
  'title' => 'Options Espace presse',
  'fields' => array (
    array (
      'key' => 'field_581886c952956',
      'label' => 'Afficher les PDF ?',
      'name' => 'dp_pdf',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_581887aaf8f96',
      'label' => 'Autoriser le téléchargement des visuels ?',
      'name' => 'visuels_zip',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '50',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 0,
      'message' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-presse.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));




endif;